### ISSUE TITLE
Uncaught TypeError: [...] Argument #2 ($post) must be of type WP_Post, null given

### ISSUE THREAD

**Issue by marceloomens** [leoloso/PoP#1284]
## Detailed description

I ran into a bug trying to open:
https://www.example.com/wp-admin/customize.php?return=%2Fwp-admin%2Fplugins.php%3Fplugin_status%3Dall%26paged%3D1%26s&autofocus%5Bcontrol%5D=background_image

Error Details
=============
An error of type E_ERROR was caused in line 554 of the file /srv/home/examplecom/domains/example.com/htdocs/www/wp-content/plugins/graphql-api/src/Services/CustomPostTypes/AbstractCustomPostType.php. Error message: Uncaught TypeError: GraphQLAPI\GraphQLAPI\Services\CustomPostTypes\AbstractCustomPostType::allowGutenbergBlocksForCustomPostType(): Argument #2 ($post) must be of type WP_Post, null given, called in /srv/home/examplecom/domains/example.com/htdocs/www/wp-content/plugins/graphql-api/src/Services/CustomPostTypes/AbstractCustomPostType.php on line 544 and defined in /srv/home/examplecom/domains/example.com/htdocs/www/wp-content/plugins/graphql-api/src/Services/CustomPostTypes/AbstractCustomPostType.php:554
Stack trace:
#0 /srv/home/examplecom/domains/example.com/htdocs/www/wp-content/plugins/graphql-api/src/Services/CustomPostTypes/AbstractCustomPostType.php(544): GraphQLAPI\GraphQLAPI\Services\CustomPostTypes\AbstractCustomPostType->allowGutenbergBlocksForCustomPostType()
#1 /srv/home/examplecom/domains/example.com/htdocs/www/wp-includes/class-wp-hook.php(303): GraphQLAPI\GraphQLAPI\Services\CustomPostTypes\AbstractCustomPostType->allowGutenbergBlocksForCustomPostTypeViaBlockEditorContext()
#2 /srv/home/examplecom/domains/example.com/htdocs/www/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#3 /srv/home/examplecom/domains/example.com/htdocs/www/wp-includes/block-editor.php(125): apply_filters()
#4 /srv/home/examplecom/domains/example.com/htdocs/www/wp-includes/block-editor.php(288): get_allowed_block_types()
#5 /srv/home/examplecom/domains/example.com/htdocs/www/wp-includes/class-wp-customize-widgets.php(844): get_block_editor_settings()
#6 /srv/home/examplecom/domains/example.com/htdocs/www/wp-includes/class-wp-hook.php(303): WP_Customize_Widgets->enqueue_scripts()
#7 /srv/home/examplecom/domains/example.com/htdocs/www/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#8 /srv/home/examplecom/domains/example.com/htdocs/www/wp-includes/plugin.php(470): WP_Hook->do_action()
#9 /srv/home/examplecom/domains/example.com/htdocs/www/wp-admin/customize.php(123): do_action()
#10 {main}
 thrown

## Reproduction path

With the GraphQL API for WordPress plugin activated, visit "Appearance->Background" in wp-admin.

## Your environment

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

- WordPress version 5.8.2
- Current theme: Twenty Twenty-One (version 1.4)
- Current plugin: GraphQL API for WordPress (version 0.8.1)
- PHP version 8.0.13

**Comment by leoloso** [comment]
@marceloomens Thanks for reporting this. The plugin's new version `v0.9`, containing this fix, will hopefully be released this week.

**Comment by leoloso** [comment]
> @marceloomens Thanks for reporting this. The plugin's new version `v0.9`, containing this fix, will hopefully be released this week.

I've had a change of plans. `v0.9` is ready, but it has some performance issues, which I'd rather fix before doing the release. I foresee it'll take a couple of weeks.

If can't wait, you can use the latest version of the plugin in development, which already has the fix to this issue. For that, download and decompress [this zip](https://github.com/leoloso/PoP/suites/4647403909/artifacts/126093000), then it's file `graphql-api.zip`.

**Comment by marceloomens** [comment]
Hi @leoloso, there's no rush from my side. Thank you for looking into this at such short notice.
