### ISSUE TITLE
Can we access WordPress custom tables with GraphQL API for Wordpress?

### ISSUE THREAD

**Issue by nickchomey** [leoloso/PoP#1565]
I am quite interested in using this plugin, but would need to be able to retrieve data from custom tables. Is this possible in any way?

**Comment by leoloso** [comment]
Yes, it is possible, but currently there's no documentation explaining how to do it, and the docs will be ready only for v1.0 of the plugin, which is still several months away (how many exactly, I don't know). So for the time being, you'd have to check the open source code, try to understand it, and try to replicate it for your custom resolvers...

**Comment by nickchomey** [comment]
Thanks for the quick reply! It's not terribly urgent for me as I'm busy developing other things right now, so I'll just wait until 1.0 is out. I look forward to it greatly - this seems like a fantastic tool.
