### ISSUE TITLE
Integration with ACF

### ISSUE THREAD

**Issue by leoloso** [leoloso/PoP#206]
# Feature Request

Integrate the free version of [Advanced Custom Fields](https://www.advancedcustomfields.com/) into the GraphQL schema, to retrieve the configuration data set-up with this plugin in the admin area.

## Context

It enables the application to interact with ACF (a WordPress plugin that enables to establish relationships among the different elements of the database) directly from the client-side, or from a Gutenberg block.

**Comment by leoloso** [comment]
Closed due to inability to get sponsors to fund this feature.

**Comment by marceloomens** [comment]
@leoloso Would you be open to re-open this issue if I were to provide sponsorship?

**Comment by leoloso** [comment]
Yes, but only if the sponsorship was substantial enough to justify the amount of work that I have to put on it. If you're interested, please [send me a message](https://graphql-api.com/contact/).
