### ISSUE TITLE
How does this project compare to wp-graphql/wp-graphql?

### ISSUE THREAD

**Issue by szepeviktor** [leoloso/PoP#394]
## Detailed description

Could you please write a brief comparison?

**Comment by leoloso** [comment]
Not sure I can make it brief, because there are many differences.

Give me 1 week, and I'll publish a proper blog post about it on graphql-api.com

**Comment by szepeviktor** [comment]
Made Slack notify me of that: https://graphql-api.com/feed.xml

**Comment by leoloso** [comment]
Here is the post: https://graphql-api.com/blog/graphql-api-vs-wpgraphql-the-fight/

**Comment by leoloso** [comment]
Closing since it's already resolved

**Comment by szepeviktor** [comment]
Okay!

[off] If you have heavy code hooked please consider lazy hooking: https://github.com/szepeviktor/Toolkit4WP/blob/master/src/HookProxy.php
