### ISSUE TITLE
Replace `class_exists("SomeClass")` with `class_exists(SomeClass::class)` everywhere

### ISSUE THREAD

**Issue by leoloso** [leoloso/PoP#606]
As pointed out by @szepeviktor: https://github.com/leoloso/PoP/pull/603#discussion_r613845833

**Comment by szepeviktor** [comment]
> everywhere

# 😲

**Comment by leoloso** [comment]
<img width="414" alt="Screenshot 2021-04-15 at 4 59 47 PM" src="https://user-images.githubusercontent.com/1981996/114843043-feb47400-9e0b-11eb-84fd-bc86e5669462.png">

**Comment by szepeviktor** [comment]
There must be a Slevomat rule for this!

**Comment by leoloso** [comment]
# 🤷
